#include "protheus.ch"

USER FUNCTION BBCODB()

LOCAL cCodBar := ""
	
	cCodBar := SE2->(IIF(!(EMPTY(E2_CODBAR)),ALLTRIM(E2_CODBAR),SUBSTR(E2_LINDIG,1,4)+SUBSTR(E2_LINDIG,33,1)+STRZERO(VAL(SUBSTR(E2_LINDIG,34,14)),14,0)+SUBSTR(E2_LINDIG,5,5)+SUBSTR(E2_LINDIG,11,10)+SUBSTR(E2_LINDIG,22,10))) 
	
RETURN(cCodBar)
